# Generated by Django 4.2.2 on 2025-12-29 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        help_text="Укажите почту", max_length=254, verbose_name="Почта"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        help_text="Укажите ФИО", max_length=240, verbose_name="ФИО"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True,
                        help_text="Напишите комментарий",
                        null=True,
                        verbose_name="Комментарий",
                    ),
                ),
            ],
            options={
                "verbose_name": "Клиент",
                "verbose_name_plural": "Клиенты",
            },
        ),
        migrations.CreateModel(
            name="Mailing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время отправки"
                    ),
                ),
                (
                    "end_datetime",
                    models.DateTimeField(
                        auto_now_add=True,
                        null=True,
                        verbose_name="Дата и время завершения рассылки",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("CREATED", "Создана"),
                            ("STARTED", "Запущена"),
                            ("COMPLETED", "Завершена"),
                        ],
                        default="CREATED",
                        max_length=25,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Активность"),
                ),
                (
                    "clients",
                    models.ManyToManyField(to="mailing.client", verbose_name="Клиенты"),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="Укажите тему сообщения",
                        max_length=100,
                        verbose_name="тема сообщения",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Напишите сообщение", verbose_name="сообщение"
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="MailingAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_datetime",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата и время попытки отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Удачная"), ("FAILED", "Неудачная")],
                        max_length=25,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "server_response",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ответ сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attempt",
                        to="mailing.mailing",
                        verbose_name="Рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка",
                "verbose_name_plural": "Попытки",
            },
        ),
        migrations.AddField(
            model_name="mailing",
            name="message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="mailing.message",
                verbose_name="Сообщение",
            ),
        ),
    ]
