# Generated by Django 4.2.2 on 2025-12-14 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='end_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата и время завершения рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_datetime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата и время отправки'),
        ),
    ]
