# Generated by Django 5.2.7 on 2025-11-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailing',
            name='client',
        ),
        migrations.AddField(
            model_name='mailing',
            name='clients',
            field=models.ManyToManyField(to='mailing.client', verbose_name='Клиенты'),
        ),
        migrations.AlterField(
            model_name='mailingattempt',
            name='status',
            field=models.CharField(choices=[('SUCCESS', 'Удачная'), ('FAILED', 'Неудачная')], max_length=25, verbose_name='Статус'),
        ),
    ]
