[tool.poetry]
name = "cw-django"
version = "0.1.0"
description = ""
authors = ["Alexander Tikhonov <AldrTikhonov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
psycopg2-binary = "^2.9.11"
python-dotenv = "^1.2.1"
pillow = "^12.0.0"
django = "4.2.2"
stripe = "^14.0.1"
black = "^25.12.0"
isort = "^7.0.0"
pytz = "^2025.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
